version: '3.8'

services:
  frontend:
    container_name: frontend
    # image: 
    build:
      context: ./frontend/
      # target: 
    volumes:
      - ./src:/app/frontend/src
    ports:
      - 3001:3000

  backend:
    container_name: backend
    build:
      context: ./backend/
    volumes:
      - .:/backend
    ports:
      - 8080:8080
    command: bash -c "cd backend && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    depends_on:
      - db

  db:
    image: postgres

    volumes:
      - ./data/db:/var/lib/postgressql/data

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    container_name: postgres_db
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_db
    depends_on:
      - db
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"